version: "3"
services:
  mariadb:
    build:
      context: ./mariadb
      args:
        MARIADB_VERSION: ${MARIADB_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mariadb/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf:ro
      - ./mariadb/data/:/var/lib/mysql/:rw
      - ./mariadb/log/:/var/log/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  nginx:
    build:
      context: ./nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:rw
      - ./www/:/var/www/html/:rw
      - ./nginx/log/:/var/log/nginx/:rw
    restart: always
    networks:
      - default